name: Test deployment

on:
  pull_request:
    branches:
      - main

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    env:
      working-directory: ./webapp
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: ${{env.working-directory}}/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: ${{env.working-directory}}
      - name: Test build website
        run: npm run build
        working-directory: ${{env.working-directory}}
